# Generated by Django 4.2.5 on 2023-09-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('stagename', models.CharField(help_text='Artist Name', max_length=50, primary_key=True, serialize=False)),
                ('social_link', models.URLField(blank=True, help_text='Artist Profile', max_length=50)),
            ],
        ),
    ]
