# Generated by Django 4.2.5 on 2023-09-18 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Album', max_length=30)),
                ('creation_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation Date ')),
                ('release_datetime', models.DateTimeField(verbose_name='Release Date')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artists.artist')),
            ],
            options={
                'order_with_respect_to': 'artist',
            },
        ),
    ]
