# Generated by Django 4.2.5 on 2023-09-27 04:36

import albums.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_created_album_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Song', max_length=50)),
                ('image', models.ImageField(upload_to='songs/images/%y/%m/%d')),
                ('audio', models.FileField(upload_to='songs/audio/%y/%m/%d', validators=[albums.models.validate_audio_file_extension])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='albums.album')),
            ],
        ),
    ]
