# Generated by Django 4.2.5 on 2023-09-27 05:04

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(help_text='Allowed Extensions .mb3 , .wav', upload_to='songs/audio/%y/%m/%d', validators=[albums.models.validate_audio_file_extension]),
        ),
    ]
